site_name: "DevCon Workshop 2022"
theme:
  name: material
  logo: Blue_Yonder_rgb.png
  features:
    - "navigation.tabs"
    - "navigation.instant"
    - "navigation.sections"
    - "toc.integrate"

extra_css:
  - stylesheets/extra.css

nav:
    - Registration: index.md
    - The Story: story.md
    - Introduction: introduction.md
    - Workshop Walkthrough: workshop-walkthrough.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search: {}
    - encryptcontent: {}
    - enumerate-headings:
        increment_across_pages: false
        exclude:
          - index.md
          - story.md
          - introduction.md
